get:
  operationId: GetTranslationsSettings
  summary: List Translation Settings
  x-sidebar-summary: List Settings
  description: >-
    Retrieve the list of translatable fields for all entities, such as products
    and collections.
  x-authenticated: true
  parameters:
    - name: entity_type
      in: query
      description: The entity to retrieve translation settings for.
      required: false
      schema:
        type: string
        title: entity_type
        description: The entity to retrieve translation settings for.
        example: product
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  x-codeSamples:
    - lang: JavaScript
      label: JS SDK
      source:
        $ref: ../code_samples/JavaScript/admin_translations_settings/get.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/admin_translations_settings/get.sh
  tags:
    - Translations
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminTranslationSettingsResponse.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-since: 2.12.3
  x-featureFlag: translation
